//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.30 at 08:04:17 PM IST 
//


package com.guavus.acume.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="static-cubes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="static-cube" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cubeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DimnesionSet">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="MeasureSet">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "staticCubes"
})
@XmlRootElement(name = "equinox")
public class Equinox {

    @XmlElement(name = "static-cubes", required = true)
    protected Equinox.StaticCubes staticCubes;

    /**
     * Gets the value of the staticCubes property.
     * 
     * @return
     *     possible object is
     *     {@link Equinox.StaticCubes }
     *     
     */
    public Equinox.StaticCubes getStaticCubes() {
        return staticCubes;
    }

    /**
     * Sets the value of the staticCubes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Equinox.StaticCubes }
     *     
     */
    public void setStaticCubes(Equinox.StaticCubes value) {
        this.staticCubes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="static-cube" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cubeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DimnesionSet">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="MeasureSet">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "staticCube"
    })
    public static class StaticCubes {

        @XmlElement(name = "static-cube")
        protected List<Equinox.StaticCubes.StaticCube> staticCube;

        /**
         * Gets the value of the staticCube property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the staticCube property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStaticCube().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Equinox.StaticCubes.StaticCube }
         * 
         * 
         */
        public List<Equinox.StaticCubes.StaticCube> getStaticCube() {
            if (staticCube == null) {
                staticCube = new ArrayList<Equinox.StaticCubes.StaticCube>();
            }
            return this.staticCube;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cubeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DimnesionSet">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="MeasureSet">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cubeId",
            "dimnesionSet",
            "measureSet"
        })
        public static class StaticCube {

            @XmlElement(required = true)
            protected String cubeId;
            @XmlElement(name = "DimnesionSet", required = true)
            protected Equinox.StaticCubes.StaticCube.DimnesionSet dimnesionSet;
            @XmlElement(name = "MeasureSet", required = true)
            protected Equinox.StaticCubes.StaticCube.MeasureSet measureSet;

            /**
             * Gets the value of the cubeId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCubeId() {
                return cubeId;
            }

            /**
             * Sets the value of the cubeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCubeId(String value) {
                this.cubeId = value;
            }

            /**
             * Gets the value of the dimnesionSet property.
             * 
             * @return
             *     possible object is
             *     {@link Equinox.StaticCubes.StaticCube.DimnesionSet }
             *     
             */
            public Equinox.StaticCubes.StaticCube.DimnesionSet getDimnesionSet() {
                return dimnesionSet;
            }

            /**
             * Sets the value of the dimnesionSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link Equinox.StaticCubes.StaticCube.DimnesionSet }
             *     
             */
            public void setDimnesionSet(Equinox.StaticCubes.StaticCube.DimnesionSet value) {
                this.dimnesionSet = value;
            }

            /**
             * Gets the value of the measureSet property.
             * 
             * @return
             *     possible object is
             *     {@link Equinox.StaticCubes.StaticCube.MeasureSet }
             *     
             */
            public Equinox.StaticCubes.StaticCube.MeasureSet getMeasureSet() {
                return measureSet;
            }

            /**
             * Sets the value of the measureSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link Equinox.StaticCubes.StaticCube.MeasureSet }
             *     
             */
            public void setMeasureSet(Equinox.StaticCubes.StaticCube.MeasureSet value) {
                this.measureSet = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "field",
                "type",
                "filepath",
                "hdfs",
                "filetype"
            })
            public static class DimnesionSet {

                @XmlElement(required = true)
                protected String field;
                @XmlElement(required = true)
                protected String type;
                @XmlElement(required = true)
                protected String filepath;
                @XmlElement(required = true)
                protected String hdfs;
                @XmlElement(required = true)
                protected String filetype;

                /**
                 * Gets the value of the field property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getField() {
                    return field;
                }

                /**
                 * Sets the value of the field property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setField(String value) {
                    this.field = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the filepath property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFilepath() {
                    return filepath;
                }

                /**
                 * Sets the value of the filepath property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFilepath(String value) {
                    this.filepath = value;
                }

                /**
                 * Gets the value of the hdfs property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHdfs() {
                    return hdfs;
                }

                /**
                 * Sets the value of the hdfs property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHdfs(String value) {
                    this.hdfs = value;
                }

                /**
                 * Gets the value of the filetype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFiletype() {
                    return filetype;
                }

                /**
                 * Sets the value of the filetype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFiletype(String value) {
                    this.filetype = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="filepath" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="hdfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="filetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "field",
                "type",
                "filepath",
                "hdfs",
                "filetype"
            })
            public static class MeasureSet {

                @XmlElement(required = true)
                protected String field;
                @XmlElement(required = true)
                protected String type;
                @XmlElement(required = true)
                protected String filepath;
                @XmlElement(required = true)
                protected String hdfs;
                @XmlElement(required = true)
                protected String filetype;

                /**
                 * Gets the value of the field property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getField() {
                    return field;
                }

                /**
                 * Sets the value of the field property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setField(String value) {
                    this.field = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the filepath property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFilepath() {
                    return filepath;
                }

                /**
                 * Sets the value of the filepath property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFilepath(String value) {
                    this.filepath = value;
                }

                /**
                 * Gets the value of the hdfs property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHdfs() {
                    return hdfs;
                }

                /**
                 * Sets the value of the hdfs property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHdfs(String value) {
                    this.hdfs = value;
                }

                /**
                 * Gets the value of the filetype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFiletype() {
                    return filetype;
                }

                /**
                 * Sets the value of the filetype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFiletype(String value) {
                    this.filetype = value;
                }

            }

        }

    }

}
