//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.30 at 08:28:33 PM IST 
//


package com.guavus.equinox.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.guavus.equinox.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.guavus.equinox.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cube }
     * 
     */
    public Cube createCube() {
        return new Cube();
    }

    /**
     * Create an instance of {@link Cube.StaticCubes }
     * 
     */
    public Cube.StaticCubes createCubeStaticCubes() {
        return new Cube.StaticCubes();
    }

    /**
     * Create an instance of {@link Cube.StaticCubes.StaticCube }
     * 
     */
    public Cube.StaticCubes.StaticCube createCubeStaticCubesStaticCube() {
        return new Cube.StaticCubes.StaticCube();
    }

    /**
     * Create an instance of {@link Cube.StaticCubes.StaticCube.DimnesionSet }
     * 
     */
    public Cube.StaticCubes.StaticCube.DimnesionSet createCubeStaticCubesStaticCubeDimnesionSet() {
        return new Cube.StaticCubes.StaticCube.DimnesionSet();
    }

    /**
     * Create an instance of {@link Cube.StaticCubes.StaticCube.MeasureSet }
     * 
     */
    public Cube.StaticCubes.StaticCube.MeasureSet createCubeStaticCubesStaticCubeMeasureSet() {
        return new Cube.StaticCubes.StaticCube.MeasureSet();
    }

}
